### ISSUE TITLE
no such file to load -- active_support/core_ext/hash/transform_values

### ISSUE THREAD

**Issue by chrishough** [mongoid/mongoid-rspec#230]
Has anyone received this error with this gem?
```
Failure/Error: # This file is copied to spec/ when you run 'rails generate rspec:install'

LoadError:
  no such file to load -- active_support/core_ext/hash/transform_values
# ./config/application.rb:11:in `<main>'
# ./config/environment.rb:1:in `<main>'
# ./config/environment.rb:2:in `(root)'
# ./spec/rails_helper.rb:1:in `block in (root)'
# ./spec/rails_helper.rb:4:in `(root)'
# ./spec/models/user_spec.rb:1:in `(root)'
# ./spec/models/user_spec.rb:3:in `(root)'
No examples found.
```

**Comment by dblock** [comment]
This should have been resolved in https://github.com/mongoid/mongoid-rspec/pull/231
